import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { HeaderNav } from './components/header-nav'; // Import HeaderNav
import { Footer } from "./components/footer";
import  BackToTopButton  from "./components/back-to-top-button";
import ProductLines from "./components/product-line-bar";



const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures text is visible while the font loads
  fallback: ['Arial', 'sans-serif'], // Custom fallback stack
  variable: '--font-montserrat', // Optional: for use with CSS variables
})


export const metadata: Metadata = {
  title: "Silver Star",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <HeaderNav />
        {children}
        <BackToTopButton />
        <Footer />
       
      </body>
    </html>
  );
}
